[project]
name = "pse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "elevenlabs>=2.9.2",
    "fastmcp>=2.11.2",
    "pydantic>=2.11.7",
]
